name: greensteel

services:
  # API Gateway 서비스
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
      - DISCOVERY_SERVICE_URL=http://discovery-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - PORT=8080
    depends_on:
      - auth-service
    networks:
      - greensteel-network

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cbam_db
      - POSTGRES_USER=cbam_user
      - POSTGRES_PASSWORD=cbam_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - greensteel-network

  # 인증 서비스
  auth-service:
    build: ./service/auth-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cbam_db
      - DB_USER=cbam_user
      - DB_PASSWORD=cbam_password
    depends_on:
      - postgres
    networks:
      - greensteel-network

  # 사용자 서비스 (향후 추가 예정)
  # user-service:
  #   build: ./service/user-service
  #   ports:
  #     - "8002:8000"
  #   networks:
  #     - greensteel-network

  # Frontend 서비스 (개발용)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - gateway
    networks:
      - greensteel-network

networks:
  greensteel-network:
    driver: bridge

volumes:
  postgres_data:
