[start]
cmd = "cd gateway/app && python main.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/gateway/app"
PORT = "8080"
AUTH_SERVICE_PORT = "8001"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
