[build]
builder = "nixpacks"

[deploy]
startCommand = "python start_services.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
PORT = "8000"
AUTH_SERVICE_PORT = "8001"
