[build]
builder = "nixpacks"

[deploy]
startCommand = "cd gateway/app && python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/gateway"
PORT = "8000"
