[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd gateway/app && python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/gateway/app"
PORT = "8080"
AUTH_SERVICE_PORT = "8001"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
