[build]
builder = "nixpacks"
buildCommand = "cd gateway && pip install -r requirements.txt"

[deploy]
startCommand = "cd gateway/app && python main.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
PORT = "8000"
